<?php

namespace AppBundle\Repository;

/**
 * DisponibilidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
